[0m10:58:51.719549 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0AE5053A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0ADBBAAB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0ADA6DEE0>]}


============================== 10:58:51.724562 | 065ca76b-bcc8-4f3d-a803-ef4222f15fbc ==============================
[0m10:58:51.724562 [info ] [MainThread]: Running with dbt=1.10.2
[0m10:58:51.724562 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\gusta\\Documents\\Dev\\jornadadedados\\workshop-airflow-dbt\\1_local_setup', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt build', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:58:51.726067 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\gusta\Documents\Dev\jornadadedados\workshop-airflow-dbt\1_local_setup\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:58:51.726067 [debug] [MainThread]: Command `dbt build` failed at 10:58:51.726067 after 0.11 seconds
[0m10:58:51.727072 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0AE6AD5E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0AE507E30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0AE5053A0>]}
[0m10:58:51.727072 [debug] [MainThread]: Flushing usage events
[0m10:58:52.301556 [debug] [MainThread]: An error was encountered while trying to flush usage events
